### Addtional Customizations

To further customize the Animal Observer app, you will need to create and add some extra files to your iPad using iTunes. 
These files are optional and if they are not used, default settings will apply. 

**1. Pinpad background image**

* To change the default background that is displayed on the opening pinpad screen, save the image you wish to use with the name "pinPadBackground.png" and add it to iTunes. 

**2. Roster folder**

* To add images for individual animals that will be displayed on the session setup screen of the app, you will need to add a folder called **"roster"** to iTunes. In this folder, you can add ".jpg" files saved with the ID code of each individual. This ID must be the same one used in the **"animals.json"** file. 

* If you wish to change the default image, save a file with the name "plus_image.jpg" in the roster folder. 

**3. Scene background image**

* To change the default scene background on the app interface, save the image you wish to use with the name "scene.png" and add it to iTunes. The scene background is a 2-D representation of the area where animals are observed. The default image is a set of concentric circles labeled with distances (in meters) on which individual animals can be placed. 

* If you add your own image, you will need to modify the "scene_width_meters" variable when you create **"layout_info.json"**. You can modify this <a id="link_to_globalvar2" href="#" class="action-button">here</a> by editing row seven in the second table in the template file.

**4. Map scene background image**

* If you use **Map Mode** in the application, you can change the default map scene background. Save the image with the name "map_scene.png" and add it to iTunes. 

